### ISSUE TITLE
Group capstone: set up the Kanban board

### ISSUE THREAD

**Issue by ZahraArshia** [ZahraArshia/TV-series-and-movies#41]
Hello 😊 
link to the project: [TV series and movies](https://github.com/ZahraArshia/TV-series-and-movies/projects/1)
## collaborators:
- Pascal: student A
- Samiullah: student B
- Zahra: student C

**Comment by GzimAsani** [comment]
# STATUS: APPROVED :100:         
## Thank you for implementing all the project requirements, you've done a great job :trophy: There is nothing else to say other than... it's time to merge it :champagne:  :tada: Congratulations

Cheers and Happy coding! :clap:  :computer:  :wine_glass: 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).
